FROM node:lts-alpine AS build

WORKDIR /build

COPY source/app/package*.json ./
RUN npm ci --no-audit --no-fund --loglevel=error --no-progress

COPY source/app ./
RUN npm run build

FROM nginx:1.29-alpine

COPY nginx.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /build/dist /usr/share/nginx/html

EXPOSE 8080
